### PR TITLE
Change user schema in GET/user/profie endpoint

### PR DESCRIPTION
**Pull request by leoank**
User password should not be returned in the response. So a new schema GetUser is created
with password field removed.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Yes, let's remove the password! Can you resubmit this pull request with the `user` not renamed?

`User` is the name of the object we are passing in the response. It's not the name of the function. Does that make sense? `User` represents the user of the application.

**Comment by leoank** [comment]
User object is used for user registration as well. If we remove the password field from the User object then registration will not work.

**Comment by julie-sullivan** [comment]
isn't that object called 'UserCredentials`?

**Comment by leoank** [comment]
Also, User object is not renamed. I have created a new GetUser object.
UserCredentials object is used for user login endpoint

**Comment by julie-sullivan** [comment]
maybe call it UserProfile? for information relating to the user that does not include password.

`GetUser` is not an appropriate name for a data exchange object.

**Comment by leoank** [comment]
Sure.

**Pull request merged**
